### ISSUE TITLE
Awnings Up/Down not working on HA (inverted?)

### ISSUE THREAD

**Issue by Noltari** [rstrouse/ESPSomfy-RTS-HA#51]
Open and Close seems to be inverted in Home Assistant, but it works correctly from the ESPSomfy-RTS website.

Awnings are open on ESPSomfy-RTS:
![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/264346/ed4ea8fd-da36-45e6-a29c-d1ede637750a)

And Home Assistant displays it correctly:
![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/264346/66f89427-a5b8-4975-a120-a4081cd9ef8b)
However, if I try to press Close on the Awnings Group, it does nothing.

But if I use the slider, it works correctly:
![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/264346/f1d5d880-4430-4be4-8a67-34ad64d364e0)
![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/264346/409d4a14-c770-4d2f-ad67-a1a3d0dcb4c8)

But then, the same happens again if I try to open them:
![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/264346/4d1073e5-b1bf-4704-bb61-4504bfb4a23a)
It's like the bug only affects the Open/Close buttons and not the slider...

**Comment by Noltari** [comment]
So I just did more tests and I can confirm that Open/Close is inverted for the awnings group but only on Home Assistant, since ESPSomfy-RTS works perfectly.

If I start with the awnings on an intermediate position and press Open:
![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/264346/43ae197c-9aeb-47c9-95f8-535d39c9a703)

Then the awnings close instead of opening:
![image](https://github.com/rstrouse/ESPSomfy-RTS-HA/assets/264346/9057ff1d-2757-4979-979f-19d9aa34c047)

**Comment by rstrouse** [comment]
HA is a menace when it comes to awnings.   Do the awnings operate properly as individuals?

**Comment by Noltari** [comment]
> HA is a menace when it comes to awnings.

Yeah...

> Do the awnings operate properly as individuals?

Yes, they operate perfectly fine as individuals.

**Comment by rstrouse** [comment]
I’ll take a look at the types assigned to the groups in HA.  Because of the way awnings are implemented on the card they operate incorrectly.  I will look at adding the work around s that I had to do for the single cover entity to the cover group entity based on whether an awning type is assigned.

**Comment by Noltari** [comment]
> I’ll take a look at the types assigned to the groups in HA.  Because of the way awnings are implemented on the card they operate incorrectly.  I will look at adding the work around s that I had to do for the single cover entity to the cover group entity based on whether an awning type is assigned.

Thanks!

**Comment by rstrouse** [comment]
Out of curiosity did you change the entity using the Show As dropdown to an awning or did HA come up with that entity type all by itself?

**Comment by Noltari** [comment]
> Out of curiosity did you change the entity using the Show As dropdown to an awning or did HA come up with that entity type all by itself?

@rstrouse honestly I don't remember, but I think I changed it manually...

**Comment by rstrouse** [comment]
Change it back to Shade and see if it reacts appropriately.   The whole thing with awnings are goofball in HA.  When I get a chance I will detect the awning setting and flip everything around.

**Comment by rstrouse** [comment]
HA really made this hard with the goofiness of the awning device class.  I will have a workaround operating in v2.4.3 of the plugin soon that preforms gymnastics on group entities.  Essentially when it encounters a group with mismatched entity positions it will translate the commands differently.  It is all just a bit silly.

**Comment by rstrouse** [comment]
Accidentally closed this when I posted a fix.  I will release it this weekend.

**Comment by Noltari** [comment]
Thanks @rstrouse, it's working now with https://github.com/rstrouse/ESPSomfy-RTS-HA/releases/tag/v2.4.3

**Comment by rstrouse** [comment]
Awesome.  I am going to close this out for now.

**Comment by radykal-com** [comment]
I'm going to resume this conversation as I'm having some problems understanding the awning config in HA.

First of all, @rstrouse thank you so much for your work, it's wonderful and it works flawless.

Now, before going into implementation details, I would like to share MY understanding of what's an awning and what each operation means.

### Awning definitions

For me, an awning is something like this
![awning](https://mx-static.markilux.com/images-resized/lg/387575/open-markilux-1300-awning-with-blue-fabric-cover-on-a-balcony.jpg)

An awning can:
- be opened (deployed)
- be closed (retracted)

In the picture above, by my understanding it's almost fully opened/deployed.

Remote control operations:
- button UP retracts
- button DOWN deploys

I hope, we all agree on the previous definitions.

### ESPSomfy-RTS

Now, let's talk about the ESPSomfy-RTS.

I have a single Awning configured like this:

<img width="399" height="388" alt="Image" src="https://github.com/user-attachments/assets/3350d9ad-abdc-421d-a991-2e6ded7f5e12" />

When the screenshot was taken, it was around 2/3 deployed (71%).

Regarding the awning position %, a 0 position means retracted, 100 means fully deployed, and values in between is a % of open, at least is what ESPSomfy-RTS is reporting (removed some fields that I think are irrelevant):
```
{
    "shadeId": 1,
    "roomId": 1,
    "name": "Toldo",
    "remoteAddress": 793721,
    "upTime": 48000,
    "downTime": 38000,
    "paired": true,
    "position": 71,
    "stepSize": 100,
    "target": 71,
    "shadeType": 3,
    "bitLength": 56,
    "proto": 0,
    "flags": 0,
    "flipCommands": false,
    "flipPosition": false,
    "repeats": 0,
    "gpioUp": 0,
    "gpioDown": 0,
    "gpioMy": 0,
    ]
  }
```

When I press the DOWN button in the remote (physical or in ESPSomfy-RTS) the awning deploys. The UP buttons, retracts.

So, until this, **all makes sense**.

### ESPSomfy-RTS-HA

Here is were things start to be weird

At the same moment the picture and the API response above were taken, HA is showing this:

<img width="282" height="438" alt="Image" src="https://github.com/user-attachments/assets/d612b2dc-a4f4-4f8f-b501-0517ab55cfc6" />
<img width="265" height="450" alt="Image" src="https://github.com/user-attachments/assets/7ac21c03-31f4-4d2a-8b3d-add14639ddbb" />

which for me, seems incorrect, instead of 71% is reporting a 29%, even the dark purple part of the slider seems reporting the 71%.

And the big "problem" for me, is that both buttons are doing the oposite operation. So:

pressing 
<img width="153" height="132" alt="Image" src="https://github.com/user-attachments/assets/194bcdbb-2c3e-4446-8855-3399764bc2a5" />
is retracting

while pressing
<img width="155" height="110" alt="Image" src="https://github.com/user-attachments/assets/2685cba5-f975-4886-9617-ba43e92a48da" />
is deploying

What leads to the wrong button enabled/disabled when fully retracted/deployed.

Also, the builtin actions that you can use in automations are doing the oposite, close action actually deploys and open action is retracting it.

### Conclusion

So, as far I understand, my ESPSomfy-RTS config is fine, since, it, alone (without taking into account HA) reports what it has to report, and each button does what it has to do.

But, in HA, I'm new to the ecosystem so I cannot tell what's wrong, but for me, it's not right.

**Comment by radykal-com** [comment]
@rstrouse I just found this issue https://github.com/home-assistant/frontend/issues/16706 you created regarding this. For me it makes sense that HA does it the right way, but seems you developed a workaround and apparently is not working for me.  Can you help me please?
