### ISSUE TITLE
Connection to remote host was lost.

### ISSUE THREAD

**Issue by ticarki** [rstrouse/ESPSomfy-RTS-HA#8]
I regularly receive the following error in my HA logs. Probably it is related to comments in [this](https://github.com/rstrouse/ESPSomfy-RTS/issues/28) issue, but now I receive this error without turning off my Wi-Fi anymore. Cards in HA are disabled when seeing the error and enabled afterwards.

```
Logger: websocket
Source: custom_components/espsomfy_rts/controller.py:119 
Integration: ESPSomfy RTS 
First occurred: 07:13:43 (7 occurrences) 
Last logged: 20:59:17

ping/pong timed out - goodbye
[Errno 110] Operation timed out - goodbye
websocket connected
Connection to remote host was lost.- goodbye
```

**Comment by rstrouse** [comment]
This will occur if the ESPSomfy device loses connection to WiFi.  Then when it reconnects the cards will be re-enable themselves. What is the current WiFi rssi strength to the ESPSomfy device?

**Comment by ticarki** [comment]
Good point, thanks! I optimized it from -58 to -48dBm and will check if the error occurs again.

**Comment by rstrouse** [comment]
I am going to close this for now.  The dropping of the socket is because it lost net connection momentarily and will reconnect.  If you get a reconnect then it will be very short.  I have found that on some networks the negotiation with 802.11b causes a lot of traffic when there are a lot of devices on it.  If you do not have any 802.11b devices I would suggest disabling it in your router.  Unfortunately, if it is enabled it must probe every device for the protocol before connecting with anything else.
