### ISSUE TITLE
Feature request: support Broadlink devices with 433 MHz

### ISSUE THREAD

**Issue by Veda82** [rstrouse/ESPSomfy-RTS-HA#9]
Please forgive me if this is too much off-topic...

First of all, great project! I also managed to control my Somfy Blinds in Home Assistant using a bash script and a Broadlink RM Pro device (1st gen);

https://www.ibroadlink.com/productinfo/762672.html

Of course my interface is very basic, and the range may be limited since from my understanding the Broadlink RF frequency is slightly different from the one used by Somfy remotes...

Anyhow, I was wondering: would you be open to consider adding Broadlink RF support to your homeassistnant component?

I can provide to you my script if needed. I think it should be fairly easy, but I understand if you want to keep the scope of your component limited...

Anyhow, thanks in advance!

**Comment by rstrouse** [comment]
I would have no way of supporting such an integration.  Feel free to take anything you need to hook up an API.  I think most of it is pretty easy to digest.  

If it were me I would grab an ESP32 and never look back though.  The components are cheap, doesn't require a high degree of tech understanding, and you can run both integrations at the same time to see what you like.

**Comment by rstrouse** [comment]
I am going to close this for now but, if I were you I would spend less than $20 and put together an ESPSomfy-RTS device.  If the only thing you are doing with the Broadlink is communicating with Somfy RTS devices then you will find that the project does a better job.  Sadly, I suppose with the Broadlink your can either use the remote or the Broadlink but not both because of the rolling code mismatches.
